In [1]:
# ==============================
# STEP 1 : Import Required Libraries
# ==============================

# Used for handling datasets
import pandas as pd

# Used for numerical operations
import numpy as np

# Used for splitting data into training and testing
from sklearn.model_selection import train_test_split

# Used for feature scaling
from sklearn.preprocessing import StandardScaler

# TensorFlow is the main deep learning library
import tensorflow as tf

# Keras is used to build the Artificial Neural Network
from tensorflow.keras.models import Sequential

# Dense is used to create ANN layers
from tensorflow.keras.layers import Dense

# Used to evaluate model performance
from sklearn.metrics import mean_squared_error, mean_absolute_error

In [2]:
# Load the dataset
df = pd.read_csv("House Price India.csv")

# Display first 5 rows
df.head()

,id,Date,number of bedrooms,number of bathrooms,living area,lot area,number of floors,waterfront present,number of views,condition of the house,...,Built Year,Renovation Year,Postal Code,Lattitude,Longitude,living_area_renov,lot_area_renov,Number of schools nearby,Distance from the airport,Price
0,6762810145,42491,5,2.50,3650,9050,2.0,0,4,5,...,1921,0,122003,52.8645,-114.557,2880,5400,2,58,2380000
1,6762810635,42491,4,2.50,2920,4000,1.5,0,0,5,...,1909,0,122004,52.8878,-114.470,2470,4000,2,51,1400000
2,6762810998,42491,5,2.75,2910,9480,1.5,0,0,3,...,1939,0,122004,52.8852,-114.468,2940,6600,1,53,1200000
3,6762812605,42491,4,2.50,3310,42998,2.0,0,0,3,...,2001,0,122005,52.9532,-114.321,3350,42847,3,76,838000
4,6762812919,42491,3,2.00,2710,4500,1.5,0,0,4,...,1929,0,122006,52.9047,-114.485,2060,4500,1,51,805000

In [3]:
# Check dataset information
df.info()

# Check dataset shape
print(df.shape)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14620 entries, 0 to 14619
Data columns (total 23 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   id                                     14620 non-null  int64
 1   Date                                   14620 non-null  int64
 2   number of bedrooms                     14620 non-null  int64
 3   number of bathrooms                    14620 non-null  float64
 4   living area                            14620 non-null  int64
 5   lot area                               14620 non-null  int64
 6   number of floors                       14620 non-null  float64
 7   waterfront present                     14620 non-null  int64
 8   number of views                        14620 non-null  int64
 9   condition of the house                 14620 non-null  int64
 10  grade of the house                     14620 non-null  int64
 11  Area of the house(excluding basement)  14620 non-null  int64
 12  Area of the basement                   14620 non-null  int64
 13  Built Year                             14620 non-null  int64
 14  Renovation Year                        14620 non-null  int64
 15  Postal Code                            14620 non-null  int64
 16  Lattitude                              14620 non-null  float64
 17  Longitude                              14620 non-null  float64
 18  living_area_renov                      14620 non-null  int64
 19  lot_area_renov                         14620 non-null  int64
 20  Number of schools nearby               14620 non-null  int64
 21  Distance from the airport              14620 non-null  int64
 22  Price                                  14620 non-null  int64
dtypes: float64(4), int64(19)
memory usage: 2.6 MB
(14620, 23)

In [4]:
# Input features
X = df.drop("Price", axis=1)

# Target variable
y = df["Price"]

In [6]:
# Split into training and testing data
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

In [10]:
# Feature Scaling

# Create scaler object
scaler = StandardScaler()

# Scale training data
X_train = scaler.fit_transform(X_train)

# Scale testing data
X_test = scaler.transform(X_test)

In [12]:

# Create the ANN model
model = Sequential()

# Input layer + First Hidden Layer
model.add(Dense(units=64, activation='relu', input_shape=(X_train.shape[1],)))

# Second Hidden Layer
model.add(Dense(units=32, activation='relu'))

# Output Layer (1 neuron for regression)
model.add(Dense(units=1, activation='linear'))

In [13]:
# Compile the ANN model
model.compile(
    optimizer='adam',
    loss='mean_squared_error',
    metrics=['mae']
)

In [14]:
# Train the ANN model
history = model.fit(
    X_train,
    y_train,
    epochs=50,
    batch_size=32,
    validation_split=0.2,
    verbose=1
)

Epoch 1/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 425112535040.0000 - mae: 538308.3125 - val_loss: 412360015872.0000 - val_mae: 534882.4375
Epoch 2/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 422336167936.0000 - mae: 536649.5000 - val_loss: 406625779712.0000 - val_mae: 531419.0000
Epoch 3/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 412143255552.0000 - mae: 530576.9375 - val_loss: 391675871232.0000 - val_mae: 522309.9062
Epoch 4/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 8s 24ms/step - loss: 391775125504.0000 - mae: 517961.5625 - val_loss: 366227030016.0000 - val_mae: 506281.9688
Epoch 5/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 5s 18ms/step - loss: 360323579904.0000 - mae: 497854.7188 - val_loss: 330035429376.0000 - val_mae: 482166.4688
Epoch 6/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 5s 16ms/step - loss: 319315148800.0000 - mae: 469610.8750 - val_loss: 286402707456.0000 - val_mae: 450367.3125
Epoch 7/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 5s 15ms/step - loss: 272288890880.0000 - mae: 434371.1562 - val_loss: 239336112128.0000 - val_mae: 411645.1250
Epoch 8/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 4s 14ms/step - loss: 224656572416.0000 - mae: 392755.0938 - val_loss: 194599796736.0000 - val_mae: 368806.3125
Epoch 9/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 182069755904.0000 - mae: 349280.7188 - val_loss: 157157605376.0000 - val_mae: 327086.2812
Epoch 10/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 146938724352.0000 - mae: 308606.5000 - val_loss: 127965904896.0000 - val_mae: 291411.9688
Epoch 11/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 120869560320.0000 - mae: 275935.9062 - val_loss: 107442061312.0000 - val_mae: 265245.9688
Epoch 12/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 5s 17ms/step - loss: 102940917760.0000 - mae: 252894.7500 - val_loss: 94030561280.0000 - val_mae: 246973.9531
Epoch 13/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 5s 15ms/step - loss: 91081146368.0000 - mae: 236609.3125 - val_loss: 85035057152.0000 - val_mae: 232926.7344
Epoch 14/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 82927632384.0000 - mae: 224134.2500 - val_loss: 78523547648.0000 - val_mae: 221287.1719
Epoch 15/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 7s 22ms/step - loss: 76893298688.0000 - mae: 213837.3281 - val_loss: 73436569600.0000 - val_mae: 211714.4688
Epoch 16/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 9s 19ms/step - loss: 72180391936.0000 - mae: 204919.7500 - val_loss: 69254258688.0000 - val_mae: 203516.7500
Epoch 17/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 68331892736.0000 - mae: 197423.3125 - val_loss: 65695985664.0000 - val_mae: 196506.5312
Epoch 18/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 65136197632.0000 - mae: 190895.7500 - val_loss: 62788452352.0000 - val_mae: 190715.7344
Epoch 19/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 62497161216.0000 - mae: 185723.5938 - val_loss: 60403470336.0000 - val_mae: 185916.2188
Epoch 20/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 6s 21ms/step - loss: 60328693760.0000 - mae: 181088.2812 - val_loss: 58299351040.0000 - val_mae: 181667.7188
Epoch 21/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 4s 14ms/step - loss: 58503446528.0000 - mae: 177516.7188 - val_loss: 56574259200.0000 - val_mae: 178342.4531
Epoch 22/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 56949727232.0000 - mae: 174133.6719 - val_loss: 55044194304.0000 - val_mae: 175468.4688
Epoch 23/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 55560925184.0000 - mae: 171149.3750 - val_loss: 53747990528.0000 - val_mae: 172975.2656
Epoch 24/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 54282194944.0000 - mae: 168609.9844 - val_loss: 52356214784.0000 - val_mae: 170307.5000
Epoch 25/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 53063106560.0000 - mae: 166028.7656 - val_loss: 51078160384.0000 - val_mae: 167816.2188
Epoch 26/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 51884089344.0000 - mae: 163228.3438 - val_loss: 49893830656.0000 - val_mae: 165438.4062
Epoch 27/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50753912832.0000 - mae: 161006.3125 - val_loss: 48672124928.0000 - val_mae: 162914.4531
Epoch 28/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49655599104.0000 - mae: 158455.0938 - val_loss: 47505207296.0000 - val_mae: 160428.6875
Epoch 29/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 48583069696.0000 - mae: 155863.8438 - val_loss: 46390435840.0000 - val_mae: 158001.4375
Epoch 30/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 47527763968.0000 - mae: 153376.1719 - val_loss: 45277204480.0000 - val_mae: 155495.7812
Epoch 31/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 46488498176.0000 - mae: 150874.2969 - val_loss: 44191612928.0000 - val_mae: 153023.9062
Epoch 32/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 45442351104.0000 - mae: 148279.5938 - val_loss: 43127369728.0000 - val_mae: 150514.3438
Epoch 33/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 44441292800.0000 - mae: 146060.8594 - val_loss: 42069454848.0000 - val_mae: 147970.4219
Epoch 34/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 43457044480.0000 - mae: 143274.4219 - val_loss: 41018056704.0000 - val_mae: 145371.5938
Epoch 35/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 42487939072.0000 - mae: 140884.0781 - val_loss: 40008048640.0000 - val_mae: 142844.9688
Epoch 36/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 41566453760.0000 - mae: 138208.2656 - val_loss: 39024492544.0000 - val_mae: 140304.5469
Epoch 37/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 40618881024.0000 - mae: 135648.2500 - val_loss: 38150336512.0000 - val_mae: 138003.7500
Epoch 38/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 39738773504.0000 - mae: 133371.7656 - val_loss: 37154197504.0000 - val_mae: 135242.4531
Epoch 39/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 38871523328.0000 - mae: 130641.5000 - val_loss: 36314394624.0000 - val_mae: 132833.0938
Epoch 40/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 38022254592.0000 - mae: 128341.5859 - val_loss: 35446202368.0000 - val_mae: 130279.4922
Epoch 41/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 37242593280.0000 - mae: 125689.5312 - val_loss: 34515939328.0000 - val_mae: 127399.2188
Epoch 42/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 7s 24ms/step - loss: 36426911744.0000 - mae: 123203.0078 - val_loss: 33786345472.0000 - val_mae: 125087.3047
Epoch 43/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 8s 17ms/step - loss: 35682754560.0000 - mae: 121086.3828 - val_loss: 32927889408.0000 - val_mae: 122253.9219
Epoch 44/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 5s 17ms/step - loss: 34951110656.0000 - mae: 118463.3047 - val_loss: 32221689856.0000 - val_mae: 119866.0078
Epoch 45/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 5s 18ms/step - loss: 34260207616.0000 - mae: 115735.4766 - val_loss: 31523137536.0000 - val_mae: 117416.6562
Epoch 46/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 10s 16ms/step - loss: 33601556480.0000 - mae: 113842.7422 - val_loss: 30794164224.0000 - val_mae: 114766.8125
Epoch 47/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 6s 18ms/step - loss: 32987529216.0000 - mae: 111297.5078 - val_loss: 30134960128.0000 - val_mae: 112301.4219
Epoch 48/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 5s 16ms/step - loss: 32367073280.0000 - mae: 108903.4922 - val_loss: 29534613504.0000 - val_mae: 110010.4688
Epoch 49/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 6s 18ms/step - loss: 31800543232.0000 - mae: 106765.0781 - val_loss: 28936871936.0000 - val_mae: 107639.3125
Epoch 50/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 5s 16ms/step - loss: 31273107456.0000 - mae: 104198.8438 - val_loss: 28431816704.0000 - val_mae: 105587.6953

In [17]:
# Predict on test data
y_pred = model.predict(X_test)

92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

In [20]:
# Evaluate the model
mae = mean_absolute_error(y_test, y_pred)

mse = mean_squared_error(y_test, y_pred)

rmse = np.sqrt(mse)

r2 = r2_score(y_test, y_pred)

print("Mean Absolute Error (MAE):", mae)
print("Mean Squared Error (MSE):", mse)
print("Root Mean Squared Error (RMSE):", rmse)
print("R2 Score:", r2)

Mean Absolute Error (MAE): 105035.1328125
Mean Squared Error (MSE): 29126154240.0
Root Mean Squared Error (RMSE): 170663.86331030948
R2 Score: 0.7933127284049988

In [19]:
comparison = pd.DataFrame({
    "Actual Price": y_test.values,
    "Predicted Price": y_pred.flatten()
})

comparison.head(10)

   Actual Price  Predicted Price
0        235000    228779.609375
1        552000    545156.562500
2        615000    602280.437500
3        555000    537121.312500
4        649950    655187.312500
5        257700    152177.203125
6        980000    884366.437500
7        535000    468171.343750
8       1030000    886558.187500
9        549950    473653.500000